---
- name: 'Download the CNI plugins archive to a local folder'
  ansible.builtin.get_url:
    url: '{{ cni_plugins_download_url }}/{{ cni_plugins_archive_name }}'
    dest: '{{ cni_plugins_download_path }}/{{ cni_plugins_archive_name }}'
    mode: 0644
  delegate_to: localhost

- name: 'Unarchive CNI plugins'
  ansible.builtin.unarchive:
    src: '{{ cni_plugins_download_path }}/{{ cni_plugins_archive_name }}'
    dest: '{{ cni_plugins_install_path }}'
    owner: 'root'
    group: 'root'
    mode: 0755
    exclude:
      - 'LICENSE'
      - 'README.md'
  become: true
